### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Nory23** [Basketcaisse21/VirtualShop-Reloaded#1]
Please can you add translatable messages? Thanks ^^

**Comment by Basketcaisse21** [comment]
Greetings @Nory23, I greatly appreciate your feedback and I will work on creating message customization to be released within the next three patches!

**Comment by Nory23** [comment]
Thankyou so much and congratz for the amazin plugin, i love it ^^

**Comment by Basketcaisse21** [comment]
Working on it right now, should be up within the next day or so.

**Comment by Basketcaisse21** [comment]
Done.

**Comment by Nory23** [comment]
Amazing thankyou so much! I have give you 5 stars in spigot for that im Nugget24 ^^

**Comment by sid-engel** [comment]
Great work.

**Comment by Basketcaisse21** [comment]
@sid-engel Thank you ;3
